# Generated by Django 6.0.5 on 2026-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_systemconfiguration_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='last_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='last_test_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='last_test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
