# Generated by Django 6.0.5 on 2026-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_systemconfiguration_last_test_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_complaint', 'New Complaint'), ('handler_assigned', 'Handler Assigned'), ('status_update', 'Status Update'), ('sla_approaching', 'SLA Approaching'), ('sla_exceeded', 'SLA Exceeded'), ('note_added', 'Note Added'), ('action_added', 'Action Added'), ('assignment', 'Assignment')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='complaints__user_id_1e1964_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['complaint', '-created_at'], name='complaints__complai_6d79ec_idx'),
        ),
    ]
