# Generated by Django 6.0.5 on 2026-06-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_add_notification_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_complaint', 'New Complaint'), ('handler_assigned', 'Handler Assigned'), ('status_update', 'Status Update'), ('sla_approaching', 'SLA Approaching'), ('sla_exceeded', 'SLA Exceeded'), ('note_added', 'Note Added'), ('action_added', 'Action Added'), ('complaint_updated', 'Complaint Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('assignment', 'Assignment')], max_length=30),
        ),
    ]
