# Generated by Django 6.0.5 on 2026-06-04 10:34

import complaints.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_add_notification_performed_by_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CT-01', 'Delayed Payment'), ('CT-02', 'Benefit Calculation Issue'), ('CT-03', 'Missing or Incorrect Contribution'), ('CT-04', 'Employer-Related Issue'), ('CT-05', 'Medical Assessment Issue'), ('CT-06', 'Claim Rejection'), ('CT-07', 'Documentation / Administrative Issue'), ('CT-08', 'Service Delivery Complaint'), ('CT-09', 'Appeal'), ('CT-10', 'Other / General Enquiry')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('default_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('default_sla_hours', models.PositiveIntegerField(default=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Level 1 - Supervisor'), (2, 'Level 2 - Manager'), (3, 'Level 3 - Director'), (4, 'Level 4 - Senior Management')])),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_reason', models.CharField(default='overdue', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('region_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (very dissatisfied) - 5 (very satisfied)')),
                ('comments', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PENSION', 'Pension Scheme'), ('OCCUPATIONAL_HAZARDS', 'Occupational Hazards Scheme'), ('MATERNITY_LEAVE', 'Maternity Leave Benefits Scheme')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('team_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('max_hours', models.PositiveIntegerField()),
                ('business_hours_only', models.BooleanField(default=False)),
                ('pause_on_pending', models.BooleanField(default=True, help_text='If true, SLA clock pauses while complaint is in "Pending Additional Information".')),
                ('reminder_50_percent', models.BooleanField(default=True)),
                ('reminder_75_percent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
                'ordering': ['priority', 'scheme', 'complaint_type'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='response_due_days',
        ),
        migrations.AddField(
            model_name='complaint',
            name='clock_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='clock_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='clock_paused_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Level 1 - Supervisor'), (2, 'Level 2 - Manager'), (3, 'Level 3 - Director'), (4, 'Level 4 - Senior Management')], default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='final_resolution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_reopened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='member_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.complaint_proof_upload_path),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_due_hours',
            field=models.PositiveIntegerField(default=240, help_text='SLA window in hours.  Auto-filled from SLAConfiguration when auto-mode is on.'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='satisfaction_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 rating submitted by complainant post-closure.', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='satisfaction_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline_date',
            field=models.DateField(blank=True, help_text='Legacy date-only SLA field.', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('teams', 'Microsoft Teams')], default='in_app', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('handler', 'Case Officer'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director'), ('admin', 'Admin'), ('complainant', 'Complainant'), ('system', 'System')], default='handler', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_50pct_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_75pct_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_complainant_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_escalation_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available_for_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Used by the escalation matrix to find the next escalation target.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['handler', 'intake_officer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_source',
            field=models.CharField(choices=[('walk_in', 'Walk-in (Front Desk)'), ('phone', 'Phone (Call Centre)'), ('email', 'Email (Shared Mailbox)'), ('web_form', 'Website / Web Form'), ('mobile_app', 'Mobile App'), ('social_media', 'Social Media'), ('letter', 'Letters / Correspondence'), ('referral', 'Institutional Referral'), ('call_center', 'Call Center (legacy)'), ('physical', 'Physical (legacy)'), ('online', 'Online (legacy)')], default='web_form', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_days',
            field=models.PositiveIntegerField(default=0, help_text='Legacy field, use sla_hours.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in (Front Desk)'), ('phone', 'Phone (Call Centre)'), ('email', 'Email (Shared Mailbox)'), ('web_form', 'Website / Web Form'), ('mobile_app', 'Mobile App'), ('social_media', 'Social Media'), ('letter', 'Letters / Correspondence'), ('referral', 'Institutional Referral'), ('call_center', 'Call Center (legacy)'), ('physical', 'Physical (legacy)'), ('online', 'Online (legacy)')], default='web_form', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Received'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_info', 'Pending Additional Information'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('reopened', 'Reopened'), ('pending', 'Pending')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_complaint', 'New Complaint'), ('handler_assigned', 'Handler Assigned'), ('status_update', 'Status Update'), ('sla_approaching', 'SLA Approaching'), ('sla_exceeded', 'SLA Exceeded'), ('sla_reminder_50', 'SLA Reminder 50%'), ('sla_reminder_75', 'SLA Reminder 75%'), ('escalation', 'Escalation Alert'), ('complainant_acknowledgement', 'Complainant Acknowledgement'), ('complainant_status_update', 'Complainant Status Update'), ('complainant_resolved', 'Complainant Resolved'), ('complainant_closed', 'Complainant Closed'), ('note_added', 'Note Added'), ('action_added', 'Action Added'), ('complaint_updated', 'Complaint Updated'), ('complaint_reopened', 'Complaint Reopened'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('assignment', 'Assignment')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal staff recipient.  Null for complainant notifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intake_officer', 'Intake Officer'), ('registrar', 'Registrar (legacy Intake)'), ('handler', 'Case Officer'), ('reviewer', 'Reviewer (legacy)'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Senior Management / Director'), ('auditor', 'Auditor'), ('admin', 'Administrator')], default='intake_officer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='complaints__notific_7be970_idx'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complainttype'),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='System (null) when triggered automatically by the SLA engine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='complaints.location'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_survey', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schemes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complainttype',
            name='applicable_schemes',
            field=models.ManyToManyField(blank=True, related_name='complaint_types', to='complaints.scheme'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.scheme'),
        ),
        migrations.AddField(
            model_name='department',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='complaints.scheme'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['scheme', 'status'], name='complaints__scheme__245a71_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['escalation_level', 'status'], name='complaints__escalat_73fb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['sla_deadline'], name='complaints__sla_dea_f49b84_idx'),
        ),
        migrations.AddField(
            model_name='slaconfiguration',
            name='complaint_type',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all complaint types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='complaints.complainttype'),
        ),
        migrations.AddField(
            model_name='slaconfiguration',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all schemes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='complaints.scheme'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint'),
        ),
        migrations.AddIndex(
            model_name='escalationlog',
            index=models.Index(fields=['complaint', '-triggered_at'], name='complaints__complai_bb974c_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationlog',
            index=models.Index(fields=['level', '-triggered_at'], name='complaints__level_fc1879_idx'),
        ),
    ]
