# Generated by Django 6.0.5 on 2026-06-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='app_label.ModelName', max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-timestamp'], name='complaints__content_334180_idx'), models.Index(fields=['actor', '-timestamp'], name='complaints__actor_i_133a05_idx'), models.Index(fields=['action', '-timestamp'], name='complaints__action_a5b4aa_idx')],
            },
        ),
    ]
